# Generated by Django 6.0.2 on 2026-03-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='productos/fotos/'),
        ),
    ]
