# Generated by Django 6.0.2 on 2026-03-29 22:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido')], db_index=True, default='PENDIENTE', max_length=15)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('foto_entrega', models.FileField(blank=True, null=True, upload_to='rutas/fotos_entrega/')),
                ('firma', models.FileField(blank=True, null=True, upload_to='rutas/firmas/')),
                ('notas_fallo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Parada de ruta',
                'verbose_name_plural': 'Paradas de ruta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ASIGNADA', 'Asignada'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada')], db_index=True, default='BORRADOR', max_length=15)),
                ('secuencia_optimizada', models.JSONField(blank=True, default=list)),
                ('distancia_total_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tiempo_estimado_min', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
