# Generated by Django 6.0.2 on 2026-03-29 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='repartidor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'REPARTIDOR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rutas.ruta'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['empresa', 'fecha', 'estado'], name='rutas_ruta_empresa_71659d_idx'),
        ),
        migrations.AddIndex(
            model_name='paradaruta',
            index=models.Index(fields=['ruta', 'estado'], name='rutas_parad_ruta_id_6cf5d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='paradaruta',
            constraint=models.UniqueConstraint(fields=('ruta', 'orden'), name='unique_ruta_orden'),
        ),
        migrations.AddConstraint(
            model_name='paradaruta',
            constraint=models.UniqueConstraint(fields=('ruta', 'pedido'), name='unique_ruta_pedido'),
        ),
    ]
