# Generated by Django 6.0.2 on 2026-03-29 22:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido')], db_index=True, default='PENDIENTE', max_length=15)),
                ('ventana_inicio', models.DateTimeField(blank=True, null=True)),
                ('ventana_fin', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='pedidos_ped_empresa_567868_idx')],
            },
        ),
    ]
