# Generated by Django 6.0.2 on 2026-03-24 14:00

from django.db import migrations, models


def normalize_legacy_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="admin").update(role="ADMIN")
    User.objects.filter(role="repartidor").update(role="DRIVER")
    User.objects.filter(role="cliente").update(role="CLIENT")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('CLIENT', 'Client')], db_index=True, default='DRIVER', max_length=10),
        ),
        migrations.RunPython(normalize_legacy_roles, migrations.RunPython.noop),
    ]
