# Generated by Django 6.0.2 on 2026-03-24 14:18

from django.db import migrations, models


def normalize_client_role(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="CLIENT").update(role="DRIVER")
    User.objects.filter(role="cliente").update(role="DRIVER")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_photo'),
    ]

    operations = [
        migrations.RunPython(normalize_client_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver')], db_index=True, default='DRIVER', max_length=10),
        ),
    ]
