# Generated by Django 6.0.2 on 2026-03-24 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'repartidor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status'], name='routes_rout_status_fbf2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['planned_date'], name='routes_rout_planned_350ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['assigned_driver', 'planned_date'], name='routes_rout_assigne_72ba7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='unique_route_sequence'),
        ),
    ]
