# Generated by Django 6.0.2 on 2026-03-24 13:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='routestop',
            name='unique_route_sequence',
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='routes_rout_planned_350ab5_idx',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='routes_rout_assigne_72ba7c_idx',
        ),
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['date'], name='routes_rout_date_aa1522_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['driver', 'date'], name='routes_rout_driver__c96d09_idx'),
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_points', to='routes.route'),
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='route',
        ),
        migrations.RemoveField(
            model_name='route',
            name='assigned_driver',
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='route',
            name='planned_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['status'], name='routes_deli_status_8107ac_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypoint',
            index=models.Index(fields=['route', 'order'], name='routes_deli_route_i_c53906_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverypoint',
            constraint=models.UniqueConstraint(fields=('route', 'order'), name='unique_route_order'),
        ),
    ]
