# Generated by Django 6.0.2 on 2026-03-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_delivery_stop'),
        ('routes', '0003_deliverypoint_remove_routestop_unique_route_sequence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteStop',
        ),
    ]
