# Generated by Django 6.0.2 on 2026-03-30 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("transferencia", "Transferencia"), ("efectivo", "Efectivo")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("completado", "Completado"), ("cancelado", "Cancelado")],
                        db_index=True,
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                ("account_number", models.CharField(blank=True, default="", max_length=50)),
                ("transaction_reference", models.CharField(blank=True, default="", max_length=120)),
                (
                    "transfer_receipt",
                    models.FileField(blank=True, null=True, upload_to="pagos/transferencias/"),
                ),
                ("transfer_date", models.DateField(blank=True, null=True)),
                ("cash_received", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("change_given", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("confirmed_by", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_method", "status"], name="pagos_paym_payment_7c4a2e_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order", "status"], name="pagos_paym_order_i_2b1a2c_idx"),
        ),
    ]
