# Generated by Django 6.0.2 on 2026-03-24 12:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('offline_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('source', models.CharField(choices=[('gps', 'GPS'), ('network', 'Red'), ('manual', 'Manual')], default='gps', max_length=20)),
                ('synced_from_offline', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
