# Generated by Django 6.0.2 on 2026-03-24 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0002_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingping',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_pings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackingping',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_pings', to='routes.route'),
        ),
        migrations.AddIndex(
            model_name='trackingping',
            index=models.Index(fields=['driver', 'recorded_at'], name='tracking_tr_driver__962efb_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingping',
            index=models.Index(fields=['route', 'recorded_at'], name='tracking_tr_route_i_4264cb_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingping',
            index=models.Index(fields=['offline_id'], name='tracking_tr_offline_75fe19_idx'),
        ),
    ]
