# Generated by Django 6.0.2 on 2026-03-24 13:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='trackingping',
            name='tracking_tr_driver__962efb_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackingping',
            name='tracking_tr_route_i_4264cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='trackingping',
            name='tracking_tr_offline_75fe19_idx',
        ),
        migrations.AddField(
            model_name='tracking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='trackingping',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trackingping',
            name='route',
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['driver', 'timestamp'], name='tracking_tr_driver__bb1ae6_idx'),
        ),
        migrations.DeleteModel(
            name='TrackingPing',
        ),
    ]
