# Generated by Django 6.0.2 on 2026-03-24 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_tracking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='device_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='offline_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='synced_from_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['offline_id'], name='tracking_tr_offline_3ec665_idx'),
        ),
    ]
