# Generated by Django 6.0.2 on 2026-03-24 12:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('attempted', 'Intentada'), ('delivered', 'Entregada'), ('failed', 'Fallida'), ('canceled', 'Cancelada')], db_index=True, default='pending', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_document', models.CharField(blank=True, max_length=40)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_photo_url', models.URLField(blank=True)),
                ('evidence_signature_url', models.URLField(blank=True)),
                ('evidence_notes', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('proof_payload', models.JSONField(blank=True, default=dict)),
                ('client_reference', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('synced_from_offline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('status_changed', 'Cambio de estado'), ('synced', 'Sincronizada')], max_length=30)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('offline_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('synced_from_offline', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
