# Generated by Django 6.0.2 on 2026-03-24 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='routes.route'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='routes.routestop'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deliveries.delivery'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='deliveries__status_bdfe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['route', 'status'], name='deliveries__route_i_c9836d_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['client_reference'], name='deliveries__client__f0d06e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['updated_at'], name='deliveries__updated_03d7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryevent',
            index=models.Index(fields=['delivery', 'occurred_at'], name='deliveries__deliver_cc0fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryevent',
            index=models.Index(fields=['offline_id'], name='deliveries__offline_dd257c_idx'),
        ),
    ]
