# Generated by Django 6.0.2 on 2026-03-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
        ('routes', '0003_deliverypoint_remove_routestop_unique_route_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='routes.deliverypoint'),
        ),
    ]
