# Generated by Django 6.0.2 on 2026-03-24 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_delivery_stop'),
        ('routes', '0004_delete_routestop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='delivery_proofs/images/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='delivery_proofs/signatures/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='delivery',
            name='deliveries__status_bdfe1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='delivery',
            name='deliveries__route_i_c9836d_idx',
        ),
        migrations.RemoveIndex(
            model_name='delivery',
            name='deliveries__client__f0d06e_idx',
        ),
        migrations.RemoveIndex(
            model_name='delivery',
            name='deliveries__updated_03d7b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryevent',
            name='deliveries__deliver_cc0fd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveryevent',
            name='deliveries__offline_dd257c_idx',
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='delivery_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='routes.deliverypoint'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='route',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='deliveryevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deliveryevent',
            name='delivery',
        ),
        migrations.AddIndex(
            model_name='deliveryproof',
            index=models.Index(fields=['status'], name='deliveries__status_11a071_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryproof',
            index=models.Index(fields=['delivery_point', 'created_at'], name='deliveries__deliver_4b31d4_idx'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryEvent',
        ),
    ]
