# Generated by Django 6.0.2 on 2026-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_deliveryproof_and_more'),
        ('routes', '0004_delete_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryproof',
            name='device_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='offline_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='synced_from_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryproof',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='delivery_proofs/images/'),
        ),
        migrations.AddIndex(
            model_name='deliveryproof',
            index=models.Index(fields=['offline_id'], name='deliveries__offline_3f2823_idx'),
        ),
    ]
